### ISSUE TITLE
Niri overview overlay launcher stops working after one use

### ISSUE THREAD

**Issue by Pacman99** [AvengeMedia/DankMaterialShell#1079]
## Compositor

- [x] niri
- [ ] Hyprland
- [ ] dwl (MangoWC)
- [ ] sway
- [ ] Other (specify)

## Distribution

NixOS

## dms version

dms 1.2-unstable+date=2025-12-16_672754b

## Description

After I open the niri overview and start typing the spotlight launcher starts as expected. Once I actually search for an app and open it then open the niri overview again the launcher doesn't work anymore. Anything I type doesn't bring the spotlight launcher back.

## Expected Behavior

I should be able to launch one app then another with the overview launcher.

## Steps to Reproduce

1. Open Niri Overview
2. Start typing to bring up spotlight launcher and open an app
3. Open overview again and launcher doesn't show up again

## Error Messages/Logs

```
nohup: ignoring input
dms 1.2-unstable+date=2025-12-16_672754b
  INFO  go: Spawning quickshell with -p /nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms
                                  
██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝ 
██║  ██║██╔══██║██║╚██╗██║██╔═██╗ 
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
  INFO  go: DMS API Server listening on: /run/user/1001/danklinux-256655.sock
  INFO  go: API Version: 24
  INFO  go: Protocol: JSON over Unix socket
  INFO  go: Request format: {"id": <any>, "method": "...", "params": {...}}
  INFO  go: Response format: {"id": <any>, "result": {...}} or {"id": <any>, "error": "..."}
  INFO  go:
  INFO  go: Initializing managers...
  INFO  go:
  INFO  go: Attempting to initialize Wayland gamma control...
  INFO  go: Wayland gamma control initialized successfully
  INFO  go: AppPicker manager initialized
  INFO  go: Attempting to initialize DWL IPC...
  INFO  go: DWL: starting registry setup
  INFO  go: Network backend detection: NetworkManager present. Using NM API.
  INFO  go: DWL: Bound wl_output id=9 registry_name=42
  INFO  go: DWL: manager not found in registry
  INFO  go: [BluezManager] found adapter: /org/bluez/hci0
  INFO  go: ExtWorkspace capability detected and will be available on subscription
  INFO  go: Attempting to initialize WlrOutput management...
  INFO  go: WlrOutput: starting registry setup
  INFO  go: WlrOutput: registry setup complete (events will be processed async)
  INFO  go: WlrOutput management initialized successfully
  INFO  go:
  INFO  go: Ready! Capabilities: [plugins gamma browser extworkspace wlroutput]
  INFO  go: Brightness manager initialized
  INFO  go: Attempting to initialize clipboard manager...
  INFO  go: DDC backend initialized
  INFO  go: WlrOutput: found zwlr_output_manager_v1
  INFO  go: WlrOutput: manager bound successfully
  INFO  go: Bound ext_data_control_manager_v1
  INFO  go: Bound wl_seat
  INFO  go: Logind backend initialized - will use for brightness control
  WARN  go: Screensaver name already owned by another process
  INFO  go: Freedesktop manager initialized
  INFO  go: Data device setup complete
  INFO  go: Clipboard manager initialized successfully
  INFO  go: Wayland event dispatcher started
  INFO  go: [BluezAgent] registered at /com/danklinux/bluez/agent with capability KeyboardDisplay
  INFO  go: Bluez manager initialized
  INFO  go: Sysfs backend initialized with 11 devices
  INFO  go: Loginctl manager initialized
  INFO  go: Udev monitor started for backlight/drm/i2c events
[32m  INFO[0m: Launching config: "/nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms/shell.qml"
[32m  INFO[0m: Shell ID: "e982b0d1adcdee36c0a90a4500505cd7" Path ID "e982b0d1adcdee36c0a90a4500505cd7"
[32m  INFO[0m: Saving logs to "/run/user/1001/quickshell/by-id/72i5yhmf7t/log.qslog"
  INFO  go: [SecretAgent] Registered with NetworkManager (id=com.danklinux.NMAgent, unique name=:1.297, fixed path=/org/freedesktop/NetworkManager/SecretAgent)
  INFO  go: Network manager initialized
  INFO  go: Evdev manager initialized
[32m  INFO[97m qml[0m: AudioService: Sound effects enabled
[32m  INFO[97m qml[0m: NetworkService: Initializing...
[32m  INFO[97m qml[0m: PolkitService: Initialized successfully
[32m  INFO[97m qml[0m: IdleService: Initialized with idle monitoring support
[33m  WARN[97m quickshell.I3.ipc[0m: $I3SOCK is unset. Trying $SWAYSOCK.
[33m  WARN[97m quickshell.I3.ipc[0m: $SWAYSOCK and I3SOCK are unset. Cannot connect to socket.
[33m  WARN[0m: $HYPRLAND_INSTANCE_SIGNATURE is unset. Cannot connect to hyprland.
[32m  INFO[0m: Configuration Loaded
[32m  INFO[97m qml[0m: Theme: Dynamic colors file loaded successfully
[33m  WARN[97m qml[0m: I18n: Falling back to built-in English strings
[32m  INFO[97m qt.multimedia.ffmpeg[0m: Using Qt multimedia with FFmpeg version 8.0 GPL version 3 or later
Input #0, wav, from '/nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms/assets/sounds/freedesktop/audio-volume-change.wav':
  Metadata:
    encoder         : Lavf62.3.100
  Duration: 00:00:00.06, bitrate: 1420 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Input #0, wav, from '/nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms/assets/sounds/freedesktop/message.wav':
  Metadata:
    encoder         : Lavf62.3.100
  Duration: 00:00:00.31, bitrate: 1413 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Input #0, wav, from '/nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms/assets/sounds/freedesktop/message-new-instant.wav':
  Metadata:
    encoder         : Lavf62.3.100
  Duration: 00:00:01.03, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Input #0, wav, from '/nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms/assets/sounds/plasma/power-plug.wav':
  Metadata:
    encoder         : Lavf62.3.100
  Duration: 00:00:03.00, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
Input #0, wav, from '/nix/store/l4f70gbkgm827ikw7jqvzr2w93b8y3m9-dms-shell-1.2-unstable+date=2025-12-16_672754b/share/quickshell/dms/assets/sounds/plasma/power-unplug.wav':
  Metadata:
    encoder         : Lavf62.3.100
  Duration: 00:00:03.00, bitrate: 1411 kb/s
  Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m quickshell.service.polkit.listener[0m: failed to register listener: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
[33m  WARN[97m quickshell.service.polkit[0m: failed to register listener on path "/org/quickshell/PolkitAgent"
[32m  INFO[97m qml[0m: Detected distribution: NixOS 26.05 (Yarara)
[32m  INFO[97m qml[0m: Theme: Setting desired theme - image mode: dark (dynamic)
[32m  INFO[97m qml[0m: CompositorService: Detected Niri with socket: /run/user/1001/niri.wayland-1.4268.sock
  INFO  go: Processing theme: image /home/pachums/Downloads/3r2n3vi1bh5i67dc1v28cn3y3jjq17cl-desktop-wallpaper-books-wallpapers-bookshelf-old-ladder-book-library-vintage-cartoon.jpg (dark)
  INFO  go: Building theme: image /home/pachums/Downloads/3r2n3vi1bh5i67dc1v28cn3y3jjq17cl-desktop-wallpaper-books-wallpapers-bookshelf-old-ladder-book-library-vintage-cartoon.jpg (dark)
  INFO  go: Using dynamic theme from image: /home/pachums/Downloads/3r2n3vi1bh5i67dc1v28cn3y3jjq17cl-desktop-wallpaper-books-wallpapers-bookshelf-old-ladder-book-library-vintage-cartoon.jpg
[32m  INFO[97m qml[0m: NiriService: Generated wpblur config at /home/pachums/.config/niri/dms/wpblur.kdl
[32m  INFO[97m qml[0m: NetworkService: Network capability detected, using DMSNetworkService
[32m  INFO[97m qml[0m: NetworkService: Switched to DMSNetworkService, networkAvailable: true
[32m  INFO[97m qml[0m: DMSService: Connected (API v24, CLI 1.2-unstable+date=2025-12-16_672754b) - ["plugins","network","loginctl","freedesktop","gamma","bluetooth","browser","extworkspace","brightness","wlroutput","evdev","clipboard"]
[32m  INFO[97m qml[0m: ExtWorkspaceService: ext-workspace available but compositor has native support
  INFO  go: Running matugen image with dank16 injection
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
  INFO  go: Matugen 3.1.0 supports --continue-on-error
[32m  INFO[97m qml[0m: NiriService: Loaded 1 outputs
[32m  INFO[97m qml[0m: CompositorService: Detected Niri with socket: /run/user/1001/niri.wayland-1.4268.sock
[32m  INFO[97m qml[0m: NiriService: Generated wpblur config at /home/pachums/.config/niri/dms/wpblur.kdl
[33m  WARN[97m scene[0m: QML DankBatteryAlerts at file:///home/pachums/.config/DankMaterialShell/plugins/DankBatteryAlerts/DankBatteryAlerts.qml[8:1]: Created graphical object was not placed in the graphics scene.
[32m  INFO[97m qml[0m: DankBar: Plugin loaded: dankBatteryAlerts
[32m  INFO[97m qml[0m: Daemon plugin loaded: dankBatteryAlerts
[32m  INFO[97m qml[0m: SessionService: Native inhibitor available: true
[32m  INFO[97m qml[0m: NiriService: Generated alttab config at /home/pachums/.config/niri/dms/alttab.kdl
[32m  INFO[97m qml[0m: NiriService: Generated layout config at /home/pachums/.config/niri/dms/layout.kdl
[32m  INFO[97m qml[0m: Theme: Dynamic colors file loaded successfully
  INFO  go: Done
[32m  INFO[97m qml[0m: Theme worker: Theme generation completed
[32m  INFO[97m qml[0m: Theme: Matugen worker completed successfully
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m scene[0m: QML PanelWindow at @Modules/WorkspaceOverlays/NiriOverviewOverlay.qml[86:13]: Binding loop detected for property "shouldShowSpotlight":
qs:@/qs/Modules/WorkspaceOverlays/NiriOverviewOverlay.qml:92:17
[33m  WARN[97m scene[0m: QML PanelWindow at @Modules/WorkspaceOverlays/NiriOverviewOverlay.qml[86:13]: Binding loop detected for property "shouldShowSpotlight":
qs:@/qs/Modules/WorkspaceOverlays/NiriOverviewOverlay.qml:92:17
[33m  WARN[97m scene[0m: QML PanelWindow at @Modules/WorkspaceOverlays/NiriOverviewOverlay.qml[86:13]: Binding loop detected for property "shouldShowSpotlight":
qs:@/qs/Modules/WorkspaceOverlays/NiriOverviewOverlay.qml:92:17
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg.draw[0m: The requested buffer size is too big, ignoring
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m scene[0m: QML PanelWindow at @Modules/WorkspaceOverlays/NiriOverviewOverlay.qml[86:13]: Binding loop detected for property "shouldShowSpotlight":
qs:@/qs/Modules/WorkspaceOverlays/NiriOverviewOverlay.qml:92:17
[33m  WARN[97m scene[0m: QML PanelWindow at @Modules/WorkspaceOverlays/NiriOverviewOverlay.qml[86:13]: Binding loop detected for property "shouldShowSpotlight":
qs:@/qs/Modules/WorkspaceOverlays/NiriOverviewOverlay.qml:92:17
[33m  WARN[97m scene[0m: QML PanelWindow at @Modules/WorkspaceOverlays/NiriOverviewOverlay.qml[86:13]: Binding loop detected for property "shouldShowSpotlight":
qs:@/qs/Modules/WorkspaceOverlays/NiriOverviewOverlay.qml:92:17
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg.draw[0m: The requested buffer size is too big, ignoring
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
[33m  WARN[97m qt.svg[0m: /etc/profiles/per-user/pachums/share/icons/hicolor/scalable/apps/Alacritty.svg:444:273: Could not resolve property: #linearGradient10962
```

## Screenshots/Recordings

At the end of the video when I open the overview after opening qutebrowser, I'm typing but no launcher shows up.
https://github.com/user-attachments/assets/19648445-8564-4cc9-b813-565756dd5e8d

**Comment by bbedward** [comment]
Should be fixed in 18231ed324469922bbb09dc5b90e75ab6d932fe7

**Comment by Pacman99** [comment]
Just updated to that commit and I'm still having the same issue

**Comment by bbedward** [comment]
As hard as I try, I'm unable to reproduce it unfortunately.

**Comment by Pacman99** [comment]
Seems to be fixed on latest master or maybe I just didn't update correctly when I tested that commit
