### ISSUE TITLE
[Bug] Media Controls & Cava

### ISSUE THREAD

**Issue by Bodify** [AvengeMedia/DankMaterialShell#112]
Couple of bugs with Media Controls:
1) The audio progress bar stays stuck at the start for all audio when launched with niri. If you run a second shell it will work fine on that.
2) Dragging the progress bar left and right a few times will cause the player (at least Spotify, seems fine on browser)  to "lag" and skip back and forth for a while even if you have stopped adjusting it.
3) I have a Go-XLR with multiple audio channels. I've used pavucontrol to route the Spotify audio to a "Music" channel. Cava seems to only register the default (System) audio channel so the visualization is just flat even though Spotify is playing. This might be a Cava issue though.

All incredibly minor bugs but figured I'd let you guys know. Thank you for the 10th time for this great work.

**Comment by bbedward** [comment]
1. Think it's fixed now
2. Should be fixed since I added a debounce, should prevent event spam
3. I set cava config to explicitly set the source name to the pipewire sink, that *might* work, if not I might need some assistance in replicating the scenario so i can see exactly.

**Comment by Bodify** [comment]
Cava is still not picking up audio from the other channel but the first two points are fixed. Let me know however I can assist with the third one.

**Comment by bbedward** [comment]
Idk how to get a pipewire config where I have a situation like you, knowing that would be helpful.

Or if you can figure out what option Cava needs to find it that’d be nearly as good.

**Comment by Bodify** [comment]
Not exactly sure what information to hand over but here is something at least. From my incredibly poor understanding it seems cava can only listen to one source at a time but take that with a grain of salt. Here is what pactl list sinks spits out while audio playing through Music only.

I say don't bother though if its a headache.  It's a niche usecase and it does not bother me at all.
```
pactl list sinks
Sink #1037
	State: SUSPENDED
	Name: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line3__sink
	Description: GoXLR Sample
	Driver: PipeWire
	Sample Specification: float32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	       balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line3__sink.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.mixer_name = "USB Mixer"
		alsa.card = "3"
		alsa.resolution_bits = "32"
		alsa.driver_name = "snd_usb_audio"
		audio.position = "FL,FR"
		alsa.mixer_device = "_ucm000F.hw:GoXLR"
		node.nick = "GoXLR"
		device.id = "44"
		device.icon_name = "audio-card-analog"
		card.profile.device = "2"
		node.name = "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line3__sink"
		audio.channels = "2"
		device.api = "alsa"
		device.routes = "1"
		alsa.class = "generic"
		device.profile.description = "Sample"
		api.alsa.split.hw-position = "[AUX0,AUX1,AUX2,AUX3,AUX4,AUX5,AUX6,AUX7,AUX8,AUX9]"
		device.description = "GoXLR"
		device.profile.name = "HiFi: Line3: sink"
		alsa.card_name = "GoXLR"
		alsa.name = "USB Audio"
		api.alsa.split.position = "[AUX8,AUX9]"
		alsa.sync.id = "00000000:00000000:00000000:00000000"
		api.alsa.path = "hw:GoXLR,0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		api.alsa.pcm.stream = "playback"
		api.alsa.card.longname = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		device.class = "sound"
		api.alsa.card.name = "GoXLR"
		node.virtual = "false"
		object.path = "alsa:acp:GoXLR:2:playback"
		alsa.components = "USB1220:8fe0"
		media.class = "Audio/Sink"
		api.alsa.split.name = "alsa_output.hw_GoXLR_0"
		alsa.subclass = "generic-mix"
		priority.session = "1000"
		alsa.long_card_name = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		alsa.id = "USB Audio"
		alsa.device = "0"
		api.alsa.open.ucm = "true"
		api.alsa.pcm.card = "3"
		node.group = "loopback-981-18"
		node.link-group = "loopback-981-18"
		resample.prefill = "true"
		resample.disable = "true"
		media.name = "GoXLR Sample input"
		stream.is-live = "true"
		node.want-driver = "true"
		node.autoconnect = "true"
		port.group = "stream.0"
		adapt.follower.spa-node = ""
		object.register = "false"
		factory.id = "12"
		clock.quantum-limit = "8192"
		node.loop.name = "data-loop.0"
		library.name = "audioconvert/libspa-audioconvert"
		client.id = "187"
		object.id = "161"
		object.serial = "1037"
		node.driver-id = "128"
		api.acp.auto-port = "false"
		api.acp.auto-profile = "false"
		api.alsa.card = "3"
		api.alsa.split-enable = "true"
		api.alsa.use-acp = "true"
		api.dbus.ReserveDevice1 = "Audio3"
		api.dbus.ReserveDevice1.Priority = "-20"
		device.bus = "usb"
		device.bus-id = "usb-TC-Helicon_GoXLR-00"
		device.bus_path = "pci-0000:0a:00.0-usb-0:7:1.0"
		device.enum.api = "udev"
		device.name = "alsa_card.usb-TC-Helicon_GoXLR-00"
		device.nick = "GoXLR"
		device.plugged.usec = "4773417"
		device.product.id = "0x8fe0"
		device.product.name = "GoXLR"
		device.serial = "TC-Helicon_GoXLR"
		device.subsystem = "sound"
		sysfs.path = "/devices/pci0000:00/0000:00:02.1/0000:03:00.0/0000:04:0c.0/0000:0a:00.0/usb1/1-7/1-7:1.0/sound/card3"
		device.vendor.id = "0x1220"
		device.vendor.name = "TC Electronic"
		spa.object.id = "8"
		device.string = "3"
	Ports:
		[Out] Line3: Sample (type: Line, priority: 500, availability unknown)
	Active Port: [Out] Line3
	Formats:
		pcm

Sink #1039
	State: SUSPENDED
	Name: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Headphones__sink
	Description: GoXLR Chat
	Driver: PipeWire
	Sample Specification: float32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	       balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Headphones__sink.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.mixer_name = "USB Mixer"
		alsa.card = "3"
		alsa.resolution_bits = "32"
		alsa.driver_name = "snd_usb_audio"
		audio.position = "FL,FR"
		alsa.mixer_device = "_ucm000F.hw:GoXLR"
		node.nick = "GoXLR"
		device.id = "44"
		device.icon_name = "audio-card-analog"
		card.profile.device = "3"
		node.name = "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Headphones__sink"
		audio.channels = "2"
		device.api = "alsa"
		device.routes = "1"
		alsa.class = "generic"
		device.profile.description = "Chat"
		api.alsa.split.hw-position = "[AUX0,AUX1,AUX2,AUX3,AUX4,AUX5,AUX6,AUX7,AUX8,AUX9]"
		device.description = "GoXLR"
		device.profile.name = "HiFi: Headphones: sink"
		alsa.card_name = "GoXLR"
		alsa.name = "USB Audio"
		api.alsa.split.position = "[AUX4,AUX5]"
		alsa.sync.id = "00000000:00000000:00000000:00000000"
		api.alsa.path = "hw:GoXLR,0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		api.alsa.pcm.stream = "playback"
		api.alsa.card.longname = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		device.class = "sound"
		api.alsa.card.name = "GoXLR"
		node.virtual = "false"
		object.path = "alsa:acp:GoXLR:3:playback"
		alsa.components = "USB1220:8fe0"
		media.class = "Audio/Sink"
		api.alsa.split.name = "alsa_output.hw_GoXLR_0"
		alsa.subclass = "generic-mix"
		priority.session = "1000"
		alsa.long_card_name = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		alsa.id = "USB Audio"
		alsa.device = "0"
		api.alsa.open.ucm = "true"
		api.alsa.pcm.card = "3"
		node.group = "loopback-981-19"
		node.link-group = "loopback-981-19"
		resample.prefill = "true"
		resample.disable = "true"
		media.name = "GoXLR Chat input"
		stream.is-live = "true"
		node.want-driver = "true"
		node.autoconnect = "true"
		port.group = "stream.0"
		adapt.follower.spa-node = ""
		object.register = "false"
		factory.id = "12"
		clock.quantum-limit = "8192"
		node.loop.name = "data-loop.0"
		library.name = "audioconvert/libspa-audioconvert"
		client.id = "96"
		object.id = "198"
		object.serial = "1039"
		node.driver-id = "128"
		api.acp.auto-port = "false"
		api.acp.auto-profile = "false"
		api.alsa.card = "3"
		api.alsa.split-enable = "true"
		api.alsa.use-acp = "true"
		api.dbus.ReserveDevice1 = "Audio3"
		api.dbus.ReserveDevice1.Priority = "-20"
		device.bus = "usb"
		device.bus-id = "usb-TC-Helicon_GoXLR-00"
		device.bus_path = "pci-0000:0a:00.0-usb-0:7:1.0"
		device.enum.api = "udev"
		device.name = "alsa_card.usb-TC-Helicon_GoXLR-00"
		device.nick = "GoXLR"
		device.plugged.usec = "4773417"
		device.product.id = "0x8fe0"
		device.product.name = "GoXLR"
		device.serial = "TC-Helicon_GoXLR"
		device.subsystem = "sound"
		sysfs.path = "/devices/pci0000:00/0000:00:02.1/0000:03:00.0/0000:04:0c.0/0000:0a:00.0/usb1/1-7/1-7:1.0/sound/card3"
		device.vendor.id = "0x1220"
		device.vendor.name = "TC Electronic"
		spa.object.id = "8"
		device.string = "3"
	Ports:
		[Out] Headphones: Chat (type: Headphones, priority: 200, availability unknown)
	Active Port: [Out] Headphones
	Formats:
		pcm

Sink #1041
	State: RUNNING
	Name: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line2__sink
	Description: GoXLR Music
	Driver: PipeWire
	Sample Specification: float32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	       balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line2__sink.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.mixer_name = "USB Mixer"
		alsa.card = "3"
		alsa.resolution_bits = "32"
		alsa.driver_name = "snd_usb_audio"
		audio.position = "FL,FR"
		alsa.mixer_device = "_ucm000F.hw:GoXLR"
		node.nick = "GoXLR"
		device.id = "44"
		device.icon_name = "audio-card-analog"
		card.profile.device = "4"
		node.name = "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line2__sink"
		audio.channels = "2"
		device.api = "alsa"
		device.routes = "1"
		alsa.class = "generic"
		device.profile.description = "Music"
		api.alsa.split.hw-position = "[AUX0,AUX1,AUX2,AUX3,AUX4,AUX5,AUX6,AUX7,AUX8,AUX9]"
		device.description = "GoXLR"
		device.profile.name = "HiFi: Line2: sink"
		alsa.card_name = "GoXLR"
		alsa.name = "USB Audio"
		api.alsa.split.position = "[AUX6,AUX7]"
		alsa.sync.id = "00000000:00000000:00000000:00000000"
		api.alsa.path = "hw:GoXLR,0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		api.alsa.pcm.stream = "playback"
		api.alsa.card.longname = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		device.class = "sound"
		api.alsa.card.name = "GoXLR"
		node.virtual = "false"
		object.path = "alsa:acp:GoXLR:4:playback"
		alsa.components = "USB1220:8fe0"
		media.class = "Audio/Sink"
		api.alsa.split.name = "alsa_output.hw_GoXLR_0"
		alsa.subclass = "generic-mix"
		priority.session = "1000"
		alsa.long_card_name = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		alsa.id = "USB Audio"
		alsa.device = "0"
		api.alsa.open.ucm = "true"
		api.alsa.pcm.card = "3"
		node.group = "loopback-981-20"
		node.link-group = "loopback-981-20"
		resample.prefill = "true"
		resample.disable = "true"
		media.name = "GoXLR Music input"
		stream.is-live = "true"
		node.want-driver = "true"
		node.autoconnect = "true"
		port.group = "stream.0"
		adapt.follower.spa-node = ""
		object.register = "false"
		factory.id = "12"
		clock.quantum-limit = "8192"
		node.loop.name = "data-loop.0"
		library.name = "audioconvert/libspa-audioconvert"
		client.id = "188"
		object.id = "122"
		object.serial = "1041"
		node.driver-id = "128"
		api.acp.auto-port = "false"
		api.acp.auto-profile = "false"
		api.alsa.card = "3"
		api.alsa.split-enable = "true"
		api.alsa.use-acp = "true"
		api.dbus.ReserveDevice1 = "Audio3"
		api.dbus.ReserveDevice1.Priority = "-20"
		device.bus = "usb"
		device.bus-id = "usb-TC-Helicon_GoXLR-00"
		device.bus_path = "pci-0000:0a:00.0-usb-0:7:1.0"
		device.enum.api = "udev"
		device.name = "alsa_card.usb-TC-Helicon_GoXLR-00"
		device.nick = "GoXLR"
		device.plugged.usec = "4773417"
		device.product.id = "0x8fe0"
		device.product.name = "GoXLR"
		device.serial = "TC-Helicon_GoXLR"
		device.subsystem = "sound"
		sysfs.path = "/devices/pci0000:00/0000:00:02.1/0000:03:00.0/0000:04:0c.0/0000:0a:00.0/usb1/1-7/1-7:1.0/sound/card3"
		device.vendor.id = "0x1220"
		device.vendor.name = "TC Electronic"
		spa.object.id = "8"
		device.string = "3"
	Ports:
		[Out] Line2: Music (type: Line, priority: 400, availability unknown)
	Active Port: [Out] Line2
	Formats:
		pcm

Sink #1043
	State: SUSPENDED
	Name: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line1__sink
	Description: GoXLR Game
	Driver: PipeWire
	Sample Specification: float32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	       balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line1__sink.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.mixer_name = "USB Mixer"
		alsa.card = "3"
		alsa.resolution_bits = "32"
		alsa.driver_name = "snd_usb_audio"
		audio.position = "FL,FR"
		alsa.mixer_device = "_ucm000F.hw:GoXLR"
		node.nick = "GoXLR"
		device.id = "44"
		device.icon_name = "audio-card-analog"
		card.profile.device = "5"
		node.name = "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Line1__sink"
		audio.channels = "2"
		device.api = "alsa"
		device.routes = "1"
		alsa.class = "generic"
		device.profile.description = "Game"
		api.alsa.split.hw-position = "[AUX0,AUX1,AUX2,AUX3,AUX4,AUX5,AUX6,AUX7,AUX8,AUX9]"
		device.description = "GoXLR"
		device.profile.name = "HiFi: Line1: sink"
		alsa.card_name = "GoXLR"
		alsa.name = "USB Audio"
		api.alsa.split.position = "[AUX2,AUX3]"
		alsa.sync.id = "00000000:00000000:00000000:00000000"
		api.alsa.path = "hw:GoXLR,0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		api.alsa.pcm.stream = "playback"
		api.alsa.card.longname = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		device.class = "sound"
		api.alsa.card.name = "GoXLR"
		node.virtual = "false"
		object.path = "alsa:acp:GoXLR:5:playback"
		alsa.components = "USB1220:8fe0"
		media.class = "Audio/Sink"
		api.alsa.split.name = "alsa_output.hw_GoXLR_0"
		alsa.subclass = "generic-mix"
		priority.session = "1000"
		alsa.long_card_name = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		alsa.id = "USB Audio"
		alsa.device = "0"
		api.alsa.open.ucm = "true"
		api.alsa.pcm.card = "3"
		node.group = "loopback-981-21"
		node.link-group = "loopback-981-21"
		resample.prefill = "true"
		resample.disable = "true"
		media.name = "GoXLR Game input"
		stream.is-live = "true"
		node.want-driver = "true"
		node.autoconnect = "true"
		port.group = "stream.0"
		adapt.follower.spa-node = ""
		object.register = "false"
		factory.id = "12"
		clock.quantum-limit = "8192"
		node.loop.name = "data-loop.0"
		library.name = "audioconvert/libspa-audioconvert"
		client.id = "98"
		object.id = "70"
		object.serial = "1043"
		node.driver-id = "128"
		api.acp.auto-port = "false"
		api.acp.auto-profile = "false"
		api.alsa.card = "3"
		api.alsa.split-enable = "true"
		api.alsa.use-acp = "true"
		api.dbus.ReserveDevice1 = "Audio3"
		api.dbus.ReserveDevice1.Priority = "-20"
		device.bus = "usb"
		device.bus-id = "usb-TC-Helicon_GoXLR-00"
		device.bus_path = "pci-0000:0a:00.0-usb-0:7:1.0"
		device.enum.api = "udev"
		device.name = "alsa_card.usb-TC-Helicon_GoXLR-00"
		device.nick = "GoXLR"
		device.plugged.usec = "4773417"
		device.product.id = "0x8fe0"
		device.product.name = "GoXLR"
		device.serial = "TC-Helicon_GoXLR"
		device.subsystem = "sound"
		sysfs.path = "/devices/pci0000:00/0000:00:02.1/0000:03:00.0/0000:04:0c.0/0000:0a:00.0/usb1/1-7/1-7:1.0/sound/card3"
		device.vendor.id = "0x1220"
		device.vendor.name = "TC Electronic"
		spa.object.id = "8"
		device.string = "3"
	Ports:
		[Out] Line1: Game (type: Line, priority: 300, availability unknown)
	Active Port: [Out] Line1
	Formats:
		pcm

Sink #1045
	State: RUNNING
	Name: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Speaker__sink
	Description: GoXLR System
	Driver: PipeWire
	Sample Specification: float32le 2ch 48000Hz
	Channel Map: front-left,front-right
	Owner Module: 4294967295
	Mute: no
	Volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
	       balance 0.00
	Base Volume: 65536 / 100% / 0.00 dB
	Monitor Source: alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Speaker__sink.monitor
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.mixer_name = "USB Mixer"
		alsa.card = "3"
		alsa.resolution_bits = "32"
		alsa.driver_name = "snd_usb_audio"
		audio.position = "FL,FR"
		alsa.mixer_device = "_ucm000F.hw:GoXLR"
		node.nick = "GoXLR"
		device.id = "44"
		device.icon_name = "audio-card-analog"
		card.profile.device = "6"
		node.name = "alsa_output.usb-TC-Helicon_GoXLR-00.HiFi__Speaker__sink"
		audio.channels = "2"
		device.api = "alsa"
		device.routes = "1"
		alsa.class = "generic"
		device.profile.description = "System"
		api.alsa.split.hw-position = "[AUX0,AUX1,AUX2,AUX3,AUX4,AUX5,AUX6,AUX7,AUX8,AUX9]"
		device.description = "GoXLR"
		device.profile.name = "HiFi: Speaker: sink"
		alsa.card_name = "GoXLR"
		alsa.name = "USB Audio"
		api.alsa.split.position = "[AUX0,AUX1]"
		alsa.sync.id = "00000000:00000000:00000000:00000000"
		api.alsa.path = "hw:GoXLR,0"
		alsa.subdevice = "0"
		alsa.subdevice_name = "subdevice #0"
		api.alsa.pcm.stream = "playback"
		api.alsa.card.longname = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		device.class = "sound"
		api.alsa.card.name = "GoXLR"
		node.virtual = "false"
		object.path = "alsa:acp:GoXLR:6:playback"
		alsa.components = "USB1220:8fe0"
		media.class = "Audio/Sink"
		api.alsa.split.name = "alsa_output.hw_GoXLR_0"
		alsa.subclass = "generic-mix"
		priority.session = "1000"
		alsa.long_card_name = "TC-Helicon GoXLR at usb-0000:0a:00.0-7, high speed"
		alsa.id = "USB Audio"
		alsa.device = "0"
		api.alsa.open.ucm = "true"
		api.alsa.pcm.card = "3"
		node.group = "loopback-981-22"
		node.link-group = "loopback-981-22"
		resample.prefill = "true"
		resample.disable = "true"
		media.name = "GoXLR System input"
		stream.is-live = "true"
		node.want-driver = "true"
		node.autoconnect = "true"
		port.group = "stream.0"
		adapt.follower.spa-node = ""
		object.register = "false"
		factory.id = "12"
		clock.quantum-limit = "8192"
		node.loop.name = "data-loop.0"
		library.name = "audioconvert/libspa-audioconvert"
		client.id = "97"
		object.id = "189"
		object.serial = "1045"
		node.driver-id = "128"
		api.acp.auto-port = "false"
		api.acp.auto-profile = "false"
		api.alsa.card = "3"
		api.alsa.split-enable = "true"
		api.alsa.use-acp = "true"
		api.dbus.ReserveDevice1 = "Audio3"
		api.dbus.ReserveDevice1.Priority = "-20"
		device.bus = "usb"
		device.bus-id = "usb-TC-Helicon_GoXLR-00"
		device.bus_path = "pci-0000:0a:00.0-usb-0:7:1.0"
		device.enum.api = "udev"
		device.name = "alsa_card.usb-TC-Helicon_GoXLR-00"
		device.nick = "GoXLR"
		device.plugged.usec = "4773417"
		device.product.id = "0x8fe0"
		device.product.name = "GoXLR"
		device.serial = "TC-Helicon_GoXLR"
		device.subsystem = "sound"
		sysfs.path = "/devices/pci0000:00/0000:00:02.1/0000:03:00.0/0000:04:0c.0/0000:0a:00.0/usb1/1-7/1-7:1.0/sound/card3"
		device.vendor.id = "0x1220"
		device.vendor.name = "TC Electronic"
		spa.object.id = "8"
		device.string = "3"
	Ports:
		[Out] Speaker: System (type: Speaker, priority: 100, availability unknown)
	Active Port: [Out] Speaker
	Formats:
		pcm
```

**Comment by bbedward** [comment]
Hmm, from that I would think it should work, does the sink show up in the control center Audio Tab? It sets the source to the current sink reported by quickshell pipewire API and from that it looks like it just makes a new sink - so from that I would expect it to work.

**Comment by Bodify** [comment]
I did some cleanup and tweaked my post install script and decided to reformat since I am not fully set up yet and also go without cava. To my surprise the equalizer on the top bar is both still there and also working for both system sounds and the music channel now. I have no idea why. I assumed cava was required for the top bar equalizer but that doesn't seem to be the case? Oh and yes they do show up in the Control Center Audio Tab.

I will continue messing with a few things but I think consider this solved for now. Would you mind clarifying a bit about cava's purpose? Is that only for the terminal equalizer? And just to clarify I do prefer having the top bar equalizer there but if it wasn't working for my setup I wouldn't mind removing it either.

**Comment by bbedward** [comment]
Without cava it just does random animations - so it works visually but not in sync with the audio

**Comment by Bodify** [comment]
Ah I see. I did install cava again after but did not restart the shell. After restarting it now I can see it is not working again yeah so that clears up some confusion. For me random animations is more than good enough, I just want any indication that something is playing. I will go without cava personally.

If you intend to look more into it and if you want more info from me or for me to try something let me know, but I would need specific instructions as I'm not good with this.

**Comment by purian23** [comment]
Brand new media player, give it a go and let us know if anything seems off. Thanks!
