### ISSUE TITLE
Network | WPA/WPA2-Enterprise Connection Issues

### ISSUE THREAD

**Issue by samminhch** [AvengeMedia/DankMaterialShell#152]
## Compositor

- [x] niri
- [ ] Hyprland
- [ ] Other (specify)

I think this applies to all compositors, but I'm using `Niri` specifically

## Description

I have a difficult time connecting to WPA/WPA2-Enterprise Networks. The issue started when I just tried to connected to my university's wifi via. the DMS network manager, however, since I use both a username and a password for that network to logon specifically, that method doesn't work and the connection fails.

>[!note]
> I'm not really sure if this is a `DankMaterialShell` issue, or if this is a `QuickShell` issue. If it is then I'll just resubmit this issue onto the `QuickShell` repo

## Expected Behavior

When clicking on a network that uses WPA/WPA2-Enterprise security, there can be a prompt for a user to enter in both their username _and_ password, and then attempt to connect to the network. Alternatively, have a form like this (the example below is from the NetworkManager prompt when connecting to such a network)

<img width="666" height="825" alt="Image" src="https://github.com/user-attachments/assets/35767534-5436-4630-bd22-905d792e1165" />

When accessing a previously connected-to network, check to see if the information has already been stored, and use those exact login details to log onto the network.

### Trying to Connect to New Network

1. Click on a Wi-Fi SSID that uses WPA/WPA2-Enterprise security

### Connect to an Existing Network

1. Click on Wi-Fi SSID that uses WPA/WPA2-Enterprise security that you have previously connnected to. You can try to connect to network using `nmtui` beforehand, and then disconnecting and trying to connect to the network
3. Try to enter in password
4. fail.
## Error Messages/Logs

>[!note]
> The lines that should probably be paid attention to are:
> ```
>  WARN quickshell.dbus.properties: QDBusError("org.freedesktop.DBus.Error.Failed", "error occurred in Get")
>  WARN quickshell.dbus.properties: Error updating property :1.59/StatusNotifierItem/org.kde.StatusNotifierItem:IconName
> ```

```
$ qs -c DankMaterialShell log
  INFO: Launching config: "/nix/store/ilcxn82v708lia8jpypxflgkhcb9i846-dankMaterialShell/etc/xdg/quickshell/DankMaterialShell/shell.qml"
  INFO: Shell ID: "2521e08a53be94248c8509a7bae816f1" Path ID "2521e08a53be94248c8509a7bae816f1"
  INFO: Saving logs to "/run/user/1000/quickshell/by-id/jx4016vy02t/log.qslog"
 DEBUG qml: Using auto location, URL: wttr.in/?format=j1
  INFO: Configuration Loaded
  WARN: Process failed to start, likely because the binary could not be found. Command: QList("khal", "list", "today")
 DEBUG qml: SessionService: Elogind detection exited with code 1
  WARN qml: DisplayService: Location mode selected but no coordinates or geoclue provider set
 DEBUG qml: CompositorService: Detected Niri with socket: /run/user/1000/niri.wayland-1.1484.sock
 DEBUG qml: Detected distribution: NixOS 25.05 (Warbler)
  WARN qml: dgop is not installed or not in PATH
 DEBUG qml: Found session path: /org/freedesktop/login1/session/_33
 DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: DisplayService: geoclue available: true
 DEBUG qml: Theme worker: wallpaper/color not found, skipping theme generation
  WARN qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7f07246ffce0 with focusing surface 0x7f070c712420
  WARN qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7f07246ffce0 with focusing surface 0x7f06e9e0ab20
  WARN quickshell.dbus.properties: Error updating property :1.59/StatusNotifierItem/org.kde.StatusNotifierItem:IconName
  WARN quickshell.dbus.properties: QDBusError("org.freedesktop.DBus.Error.Failed", "error occurred in Get")
  WARN quickshell.dbus.properties: Error updating property :1.59/StatusNotifierItem/org.kde.StatusNotifierItem:IconName
  WARN quickshell.dbus.properties: QDBusError("org.freedesktop.DBus.Error.Failed", "error occurred in Get")
  WARN quickshell.dbus.properties: Error updating property :1.59/StatusNotifierItem/org.kde.StatusNotifierItem:IconName
  WARN quickshell.dbus.properties: QDBusError("org.freedesktop.DBus.Error.Failed", "error occurred in Get")
  WARN quickshell.dbus.properties: Error updating property :1.59/StatusNotifierItem/org.kde.StatusNotifierItem:IconName
  WARN quickshell.dbus.properties: QDBusError("org.freedesktop.DBus.Error.Failed", "error occurred in Get")
  WARN qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7f072e5262a0 with focusing surface 0x7f070c507aa0
```

## Screenshots/Recordings

<img width="1299" height="825" alt="Image" src="https://github.com/user-attachments/assets/e1ede9b7-33bf-4924-b15b-1f5f4311f549" />

**Comment by bbedward** [comment]
Yea it's not quickshell, they dont support NetworkManager yet. I'll have to see how to detect and integrate with them (wpa2 enterprise stuff).

**Comment by samminhch** [comment]
Okay here's another view from nm-applet for username and password 😄, thank you for picking up this issue I really appreciate this! I'm not very well-versed with network connection tools / systems, but I think this can be implemented without `NetworkManager` as long as the right information is passed for wpa2 enterprise
<img width="527" height="298" alt="Image" src="https://github.com/user-attachments/assets/50cbb901-c23d-476e-884b-7a33ad9f61d1" />

**Comment by larsivi** [comment]
I have the same issue I think, using DMS on Niri (just installed both), but just with normal wifi (no enterprise). I run on Arch/EndeavourOS with KDE/Plasma and NetworkManager.

From the QuickShell dependency list, it seems it supports NetworkManager? Note that if I have connected to the Wifi using Plasma, then log into Niri, the widget shows the correct network being connected, and I can disconnect it. But it won't reconnect, and it doesn't accept my key. For some reason nothing of this shows in the log?

As an aside, I love the looks and features of DMS!

**Comment by TheSkyHeart** [comment]
> I have the same issue I think, using DMS on Niri (just installed both), but just with normal wifi (no enterprise). I run on Arch/EndeavourOS with KDE/Plasma and NetworkManager.
> 
> From the QuickShell dependency list, it seems it supports NetworkManager? Note that if I have connected to the Wifi using Plasma, then log into Niri, the widget shows the correct network being connected, and I can disconnect it. But it won't reconnect, and it doesn't accept my key. For some reason nothing of this shows in the log?
> 
> As an aside, I love the looks and features of DMS!


I also have the same issue, I use EndeavourOS with KDE/Plasma and install DMS, when I try to connect to WIFI I get Failed to connect to (SSID) mean while I'm able to use nmtui to connect to the same network.

**Comment by bbedward** [comment]
I don't have a meaningful way to test this stuff because my router doesn't have wpa enterprise options, I'd appreciate an assist on it really. Well now we just spawn processes because qs doesn't have nm integration, so a sequence of commands to determine an wpae network and how to connect with wpae would be helpful

**Comment by TheSkyHeart** [comment]
Thanks for the good work @bbedward 

I don't use a WPAE, it's a normal WIFI with WPA2, I did also tried Noctalia which does work fine there.

**Comment by larsivi** [comment]
Yeah, mine too is just WPA2. In any case, I'm workarounding using nmcli

There is this command that prompts for a password:
$ nmcli --ask c up FooSSID

Then this one _with_ password:
nmcli dev wifi connect FooSSID password FooPassword

I forgot if I actually changed anything relating to it, but now it also remembers my pw's and auto-connects. The indicator in top bar has mostly followed suit, although it didn't pick up the network change this morning when I got to the office. So the connector now shows disconnected, while I'm quite clearly is.

I'm interested in helping out (have some QML experience from the days of old), but don't exactly see where I could find the time for actual coding.

**Comment by bbedward** [comment]
Now that we're injecting the DMS_SOCKET into the shell when it spins up, my plan is to integrate proper network manager dbus bindings into dms via [gonetworkmanager](https://github.com/Wifx/gonetworkmanager)

That can replace the janky nmcli implementation and hopefully close this one out

**Comment by bbedward** [comment]
Alright, as of 0.1.2 and current master. This might be resolved (but I can't test, as I do not have wpa enterprise).

It'll require updating both dms bin and dms (qml). It flips to native networkmanager bindings

**Comment by larsivi** [comment]
Nice! I can update and test the WPA2 stuff at least no later than this weekend.

**Comment by samminhch** [comment]
> Alright, as of 0.1.2 and current master. This might be resolved (but I can't test, as I do not have wpa enterprise).
> 
> It'll require updating both dms bin and dms (qml). It flips to native networkmanager bindings

I'll test it out on some WPA2 enterprise connections when I get the update. Thank you so much for your work @bbedward!

**Comment by samminhch** [comment]
Hm, after updating and trying to connect with my credentials, it says that it failed to connect to the network. Is there a way for me to view the log for DMS that was installed on NixOS flakes so that I can help pin down the cause for this?

**Comment by bbedward** [comment]
Check https://github.com/AvengeMedia/danklinux/commit/1a0fbf1a90601ba2eff2260e7c307d9146b053e9

if you clone that repo, do `make` and then `dms kill && ./bin/dms run` you should get logs. Hopefully that point in the direction

**Comment by bbedward** [comment]
Actually, [newer one](https://github.com/AvengeMedia/danklinux/commit/a1205879f3eab60f39d510cce3d4c12d71bd433d) - this should either fix it, or at the least comprehensively log what the issue is.  (It will, probably dump the credentials into the logs - you can redact those if you share them)

**Comment by samminhch** [comment]
Here's the logs of DMS when trying to connect to the network with a username/password
```
 DEBUG  go: DMS API Request: method=network.wifi.connect id=1760038867895
 ERROR  go: DMS API Error: id=1760038867895 error=failed to connect: 802-1x.phase2-auth, 802-1x.phase2-autheap: exactly one property must be set
```

**Comment by larsivi** [comment]
With just normal WPA2 it works perfectly for me now! (this may have been the case for a while? At least it also worked with 0.0.29 it turned out.) I was a bit surprised to find that dms-shell was no longer an AUR package, but installed -git and it works. I would also have expected to see the version somewhere, probably on the About page in Settings.

**Comment by bbedward** [comment]
> With just normal WPA2 it works perfectly for me now! (this may have been the case for a while? At least it also worked with 0.0.29 it turned out.) I was a bit surprised to find that dms-shell was no longer an AUR package, but installed -git and it works. I would also have expected to see the version somewhere, probably on the About page in Settings.

It became dms-shell-bin because of arch conventions I guess

**Comment by bbedward** [comment]
Try this for WPA enterprise, I think we are close: https://github.com/AvengeMedia/danklinux/commit/0c59fb35bf8d90bcbd2117c678d13278bfeed68b

**Comment by samminhch** [comment]
I'm having trouble building it now :(
```
[samminhch@minhtop:~/Code/repos/danklinux]$ nix develop
[samminhch@minhtop:~/Code/repos/danklinux]$ make
Building dms...
CGO_ENABLED=0 go build -ldflags="-s -w -X main.Version=v0.1.7-1-g0c59fb3 -X main.buildTime=2025-10-09_20:31:52 -X main.commit=0c59fb3" -o bin/dms cmd/dms/*.go
go: parsing $GOFLAGS: unknown flag -w"
make: *** [Makefile:27: build] Error 1
```

**Comment by samminhch** [comment]
Okay, I was able to test it @bbedward, and I think we are super close to the solution. I seem to be able to connect, but I don't have internet access because a domain was not set. I think if we had an option to specify what domain of the WPA2-enterprise connection we are connecting to (or if there is an automatic way of determining that) we would be able to arrive at the solution. Here are the logs for connecting to a WPA2 Enterprise network (I removed my SSID and username and password for privacy):
```
2025/10/13 14:54:24 [ConnectWiFi] Starting connection to SSID: {some SSID}, hasUsername: true, hasPassword: true
2025/10/13 14:54:24 [ConnectWiFi] Searching for existing connection for SSID: {some SSID}
2025/10/13 14:54:24 [ConnectWiFi] No existing connection found (or error: connection not found), creating new connection
2025/10/13 14:54:24 [createAndConnectWiFi] Starting for SSID: {some SSID}}
2025/10/13 14:54:24 [createAndConnectWiFi] Ensuring WiFi device is available
2025/10/13 14:54:24 [createAndConnectWiFi] Getting access points
2025/10/13 14:54:24 [createAndConnectWiFi] Found 23 access points
2025/10/13 14:54:24 [createAndConnectWiFi] Found target access point for SSID: {some SSID}
2025/10/13 14:54:24 [createAndConnectWiFi] AP Security flags - flags: 0x1, wpaFlags: 0x0, rsnFlags: 0x288
2025/10/13 14:54:24 [createAndConnectWiFi] Network analysis - secured: true, isEnterprise: true, isPsk: false, isSae: false
2025/10/13 14:54:24 [createAndConnectWiFi] Configuring WPA-EAP (enterprise) with username: {some username}
2025/10/13 14:54:24 [createAndConnectWiFi] WPA-EAP settings configured: eap=peap, phase2-auth=mschapv2, identity={some username}, system-ca-certs=true
2025/10/13 14:54:24 [createAndConnectWiFi] Calling AddAndActivateWirelessConnection with settings: map[802-11-wireless:map[mode:infrastructure security:802-11-wireless-security ssid:[67 111 109 101 116 78 101 116]] 802-11-wireless-security:map[key-mgmt:wpa-eap] 802-1x:map[eap:[peap] identity:{some username} password:{some password} phase2-autheap:mschapv2 system-ca-certs:true] connection:map[id:{some SSID} type:802-11-wireless] ipv4:map[method:auto] ipv6:map[method:auto]]
2025/10/13 14:54:24 [createAndConnectWiFi] Using access point: /org/freedesktop/NetworkManager/AccessPoint/527
2025/10/13 14:54:24 [createAndConnectWiFi] Successfully added and activated wireless connection
2025/10/13 14:54:24 [ConnectWiFi] Successfully created and connected to new network
```

Thank you again for your hard work and persistance on this issue!

**Comment by bbedward** [comment]
I have a suite of enhancements to expose more options

<img width="401" height="487" alt="Image" src="https://github.com/user-attachments/assets/5611d59d-ff74-4b76-ba9f-2807df6696ed" />

[c513594e9f6b1a5f5b8f394242ae0954afad613f](https://github.com/AvengeMedia/danklinux/commit/c513594e9f6b1a5f5b8f394242ae0954afad613f)

7e885d3cee4b603718d0094f84c871c11443d10a

I can't really test it since I dont have an enterprise network to connect to, but hopefully - this gives enough to get it done in any case

**Comment by samminhch** [comment]
Thanks, I just tried to test it on an enterprise network, and I think we are even closer--however inputting the domain of the network and pressing "connect" doesn't actually save the domain information. I verified this using the nm-applet connection editor (censored the SSID and username for privacy)

<img width="561" height="687" alt="Network manager applet's connection manager with an undefined domain" src="https://github.com/user-attachments/assets/b98623f8-4994-4033-9526-eb057724be86" />

Here's the relavant logs:
```
2025/10/14 15:06:58 [ConnectWiFi] Starting connection to SSID: ${SSID_HERE}, hasUsername: true, hasPassword: true
2025/10/14 15:06:58 [ConnectWiFi] Searching for existing connection for SSID: ${SSID_HERE}
2025/10/14 15:06:58 [ConnectWiFi] No existing connection found (or error: connection not found), creating new connection
2025/10/14 15:06:58 [createAndConnectWiFi] Starting for SSID: ${SSID_HERE}
2025/10/14 15:06:58 [createAndConnectWiFi] Ensuring WiFi device is available
2025/10/14 15:06:58 [createAndConnectWiFi] Getting access points
2025/10/14 15:06:58 [createAndConnectWiFi] Found 18 access points
2025/10/14 15:06:58 [createAndConnectWiFi] Found target access point for SSID: ${SSID_HERE}
2025/10/14 15:06:58 [createAndConnectWiFi] AP Security flags - flags: 0x1, wpaFlags: 0x0, rsnFlags: 0x288
2025/10/14 15:06:58 [createAndConnectWiFi] Network analysis - secured: true, isEnterprise: true, isPsk: false, isSae: false
2025/10/14 15:06:58 [createAndConnectWiFi] Configuring WPA-EAP (enterprise) with username: ${USERNAME_HERE}
2025/10/14 15:06:58 [createAndConnectWiFi] WPA-EAP settings configured: eap=peap, phase2-auth=mschapv2, identity=${USERNAME_HERE}, system-ca-certs=true
2025/10/14 15:06:58 [createAndConnectWiFi] Calling AddAndActivateWirelessConnection with settings: map[802-11-wireless:map[mode:infrastructure security:802-11-wireless-security ssid:[67 111 109 101 116 78 101 116]] 802-11-wireless-security:map[key-mgmt:wpa-eap] 802-1x:map[eap:[peap] identity:${USERNAME_HERE} password:${PASSWORD_HERE} phase2-autheap:mschapv2 system-ca-certs:true] connection:map[id:${SSID_HERE} type:802-11-wireless] ipv4:map[method:auto] ipv6:map[method:auto]]
2025/10/14 15:06:58 [createAndConnectWiFi] Using access point: /org/freedesktop/NetworkManager/AccessPoint/1516
2025/10/14 15:06:58 [createAndConnectWiFi] Successfully added and activated wireless connection
2025/10/14 15:06:58 [ConnectWiFi] Successfully created and connected to new network
```

Note that although it says it successfully created and connected to the enterprise network, the connection fails, and it immediately switches to another known network (the logs did not show that, but I did observe it with my own eyes)

**Comment by bbedward** [comment]
Are you using the dms CLI >= https://github.com/AvengeMedia/danklinux/commit/c513594e9f6b1a5f5b8f394242ae0954afad613f ? I don't see the logs for domain-suffix-match

**Comment by samminhch** [comment]
I'd like to, but I can't seem to build `danklinux` for some reason:
```
$ nix develop
$ make
Building dms...
CGO_ENABLED=0 go build -ldflags="-s -w -X main.Version=v0.1.14-1-gc513594 -X main.buildTime=2025-10-14_20:49:27 -X main.commit=c513594" -o bin/dms ./cmd/dms
go: parsing $GOFLAGS: unknown flag -w"
make: *** [Makefile:30: build] Error 1
```

**Comment by bbedward** [comment]
Might be some weird shell thing with the quoting, can try https://github.com/AvengeMedia/danklinux/commit/afe2da69ff0b1a6d0bdcba81f42d94c70912b87e

alternatively you can just do `go run ./cmd/dms run` to not build it at all.

**Comment by samminhch** [comment]
I built it without using make (just copied and pasted the command from `CGO_ENABLED`), and the logs seem the same:
```
[samminhch@minhtop:~/Code/repos/danklinux]$ ./bin/dms version

██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝
██║  ██║██╔══██║██║╚██╗██║██╔═██╗
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
DankLinux Manager v0.1.14-3-gafe2da6

[samminhch@minhtop:~/Code/repos/danklinux]$ ./bin/dms run

██████╗  █████╗ ███╗   ██╗██╗  ██╗
██╔══██╗██╔══██╗████╗  ██║██║ ██╔╝
██║  ██║███████║██╔██╗ ██║█████╔╝
██║  ██║██╔══██║██║╚██╗██║██╔═██╗
██████╔╝██║  ██║██║ ╚████║██║  ██╗
╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
  INFO  go: DMS API Server listening on: /run/user/1000/danklinux-73464.sock
  INFO  go: Protocol: JSON over Unix socket
  INFO  go: Request format: {"id": <any>, "method": "...", "params": {...}}
  INFO  go: Response format: {"id": <any>, "result": {...}} or {"id": <any>, "error": "..."}
  INFO  go: Freedesktop manager initialized
  INFO  go: Network manager initialized
  INFO  go: Loginctl manager initialized
  INFO: Launching config: "/nix/store/k81psmk25fbvisqnq4x0r1znibhnaaca-dankMaterialShell/etc/xdg/quickshell/DankMaterialShell/shell.qml"
  INFO: Shell ID: "96b38cea8e8a78949f7e03c4ff8bf8b8" Path ID "96b38cea8e8a78949f7e03c4ff8bf8b8"
  INFO: Saving logs to "/run/user/1000/quickshell/by-id/wok1so354t/log.qslog"
  WARN scene: QML Connections at @Services/SessionService.qml[296:5]: Detected function "onLoginctlLockIntegrationChanged" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
  WARN scene: QML Connections at @Services/SessionService.qml[296:5]: Detected function "onLockBeforeSuspendChanged" in Connections element. This is probably intended to be a signal handler but no signal of the target matches the name.
  WARN qml: AudioService: QtMultimedia not available - sound effects disabled
  WARN qml: IdleService: IdleMonitor not available - power management disabled. This requires a newer version of Quickshell.
 DEBUG qml: NetworkService: Initializing...
 DEBUG qml: NetworkService: DMS_SOCKET found, waiting for capabilities...
  INFO: Configuration Loaded
  WARN qml: I18n: Falling back to built-in English strings
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of ~/.local/state/DankMaterialShell/notepad-files/untitled-1757995899565.txt failed: File does not exist.
  WARN scene: QML FileView at @Services/NotepadStorageService.qml[266:9]: Read of ~/.local/state/DankMaterialShell/notepad-files/untitled-1757995899565.txt failed: File does not exist.
 DEBUG qml: Detected distribution: NixOS 25.05 (Warbler)
  WARN scene: @Modules/DankBar/Widgets/IdleInhibitor.qml[36:-1]: ReferenceError: barThickness is not defined
  WARN scene: @Modules/DankBar/Widgets/IdleInhibitor.qml[36:-1]: ReferenceError: barThickness is not defined
 DEBUG  go: DMS API Request: method=subscribe id=0
 DEBUG  go: DMS API Request: method=loginctl.getState id=1760475629686
 DEBUG qml: NetworkService: Network capability detected, using NetworkManagerService
 DEBUG  go: DMS API Request: method=loginctl.setLockBeforeSuspend id=1760475629687
 DEBUG qml: NetworkService: Switched to NetworkManagerService, networkAvailable: true
 DEBUG  go: DMS API Request: method=network.getState id=1760475629688
 DEBUG qml: DMSService: Connected (API v3) - ["plugins","network","loginctl","freedesktop"]
 DEBUG qml: SessionService: Synced lock before suspend: true
 DEBUG  go: DMS API Request: method=network.wifi.scan id=1760475629690
 DEBUG  go: DMS API Request: method=network.getState id=1760475629735
 DEBUG qml: CompositorService: Detected Niri with socket: /run/user/1000/niri.wayland-1.2502.sock
 DEBUG qml: NiriService: Generating binds config...
  WARN qml: NiriService: Failed to write binds config, exit code: 1
 DEBUG qml: DankBar: Plugin loaded: calculator
 DEBUG qml: DankBar: Plugin loaded: niriWindows
  WARN scene: QML DankBatteryAlerts at file:///home/samminhch/.config/DankMaterialShell/plugins/Dank Battery Alerts/DankBatteryAlerts.qml[8:1]: Created graphical object was not placed in the graphics scene.
 DEBUG qml: DankBatteryAlerts: Started monitoring battery level
 DEBUG qml: DankBatteryAlerts: Critical alerts: true at 10%
 DEBUG qml: DankBatteryAlerts: Warning alerts: true at 20%
 DEBUG qml: DankBar: Plugin loaded: dankBatteryAlerts
 DEBUG qml: DankBatteryAlerts: Started monitoring battery level
 DEBUG qml: DankBatteryAlerts: Critical alerts: true at 10%
 DEBUG qml: DankBatteryAlerts: Warning alerts: true at 20%
 DEBUG qml: Daemon plugin loaded: dankBatteryAlerts                                                                                              DEBUG qml: NiriService: Loaded 1 outputs
 DEBUG qml: SessionService: Native inhibitor available: false
 DEBUG qml: NiriService: Generating layout config...
 DEBUG qml: NiriService: Generated layout config at /home/samminhch/.config/niri/dms/layout.kdl
 DEBUG qml: SessionService: Elogind detection exited with code 1
 DEBUG  go: DMS API Request: method=freedesktop.getState id=1760475632425
 DEBUG  go: DMS API Request: method=freedesktop.getState id=1760475632426
 DEBUG  go: DMS API Request: method=network.wifi.scan id=1760475632441
 DEBUG  go: DMS API Request: method=freedesktop.settings.getColorScheme id=1760475632442
 DEBUG  go: DMS API Request: method=network.getState id=1760475632489
 DEBUG  go: DMS API Request: method=network.wifi.scan id=1760475633346
 DEBUG  go: DMS API Request: method=network.getState id=1760475633388
 DEBUG  go: DMS API Request: method=network.wifi.connect id=1760475645584
2025/10/14 16:00:45 [ConnectWiFi] Starting connection to SSID: ${SSID_HERE}, hasUsername: true, hasPassword: true
2025/10/14 16:00:45 [ConnectWiFi] Searching for existing connection for SSID: ${SSID_HERE}
2025/10/14 16:00:45 [ConnectWiFi] No existing connection found (or error: connection not found), creating new connection
2025/10/14 16:00:45 [createAndConnectWiFi] Starting for SSID: ${SSID_HERE}
2025/10/14 16:00:45 [createAndConnectWiFi] Ensuring WiFi device is available
2025/10/14 16:00:45 [createAndConnectWiFi] Getting access points
2025/10/14 16:00:45 [createAndConnectWiFi] Found 25 access points                                                                               2025/10/14 16:00:45 [createAndConnectWiFi] Found target access point for SSID: ${SSID_HERE}
2025/10/14 16:00:45 [createAndConnectWiFi] AP Security flags - flags: 0x1, wpaFlags: 0x0, rsnFlags: 0x288
2025/10/14 16:00:45 [createAndConnectWiFi] Network analysis - secured: true, isEnterprise: true, isPsk: false, isSae: false
2025/10/14 16:00:45 [createAndConnectWiFi] WPA-EAP settings: eap=peap, phase2-autheap=mschapv2, identity=${USERNAME_HERE}, system-ca-certs=true, domain-suffix-match=""
2025/10/14 16:00:45 [createAndConnectWiFi] Calling AddAndActivateWirelessConnection with settings: map[802-11-wireless:map[mode:infrastructure security:802-11-wireless-security ssid:[67 111 109 101 116 78 101 116]] 802-11-wireless-security:map[key-mgmt:wpa-eap] 802-1x:map[eap:[peap] identity:${USERNAME_HERE} password:${PASSWORD_HERE} phase2-autheap:mschapv2 system-ca-certs:true] connection:map[id:${SSID_HERE} type:802-11-wireless] ipv4:map[method:auto] ipv6:map[method:auto]]
2025/10/14 16:00:45 [createAndConnectWiFi] Using access point: /org/freedesktop/NetworkManager/AccessPoint/1794
2025/10/14 16:00:45 [createAndConnectWiFi] Successfully added and activated wireless connection
2025/10/14 16:00:45 [ConnectWiFi] Successfully created and connected to new network

Received signal interrupt, shutting down...
```

**Comment by bbedward** [comment]
Was missing a piece - resolved in https://github.com/AvengeMedia/danklinux/commit/88ee95c303dda4557bf177ffb6737e2438f45f11 so now it'll pass domain through

**Comment by samminhch** [comment]
Hello, I checked out that commit and the username@domain option still doesn't set the domain. I think the issue with that implementation is that it sets the domain in the username section (I checked for both domain options, and it does `username@domain` and `domain\username`). However, what needs to be set in the network configuration is the `Domain` field (2) of the pasted image:

<img width="666" height="825" alt="Image" src="https://github.com/user-attachments/assets/ce3cd405-1de6-4331-9fe4-ace17aa9a9ce" />

Right now, the network connection for the enterprise network that I'm connecting to looks like this from `nm-applet`:

<img width="564" height="689" alt="Image" src="https://github.com/user-attachments/assets/a8ae70cf-985d-405d-ba85-02848c123d8b" />

Ideally, the connection should look like this:

<img width="564" height="672" alt="Image" src="https://github.com/user-attachments/assets/376c02e7-c731-4fa4-8f7b-19a062a112a5" />

**Comment by bbedward** [comment]
Could you dump this

`nmcli connection show "Name Of Conn" > ~/nm.txt` - and you can redact anything that might be in that file then dump it.

That should be - definitive for me to figure out what needs to be set. Because, nothing in the [NM doc](https://people.freedesktop.org/~lkundrak/nm-dbus-api/nm-settings.html) directly maps to the fields from network  manager GUI - but the ones from nmcli should.

**Comment by samminhch** [comment]
Here's the dumpfile: [nm.txt](https://github.com/user-attachments/files/22957529/nm.txt)

I labeled some of the things that you would probably be looking for:
- SSID = `<SSID_here>`
- domain = `<domain_here>`

I think that there's something interesting here on these lines:
```
IP4.DOMAIN[1]:                          <domain_here>
IP4.SEARCHES[1]:                        <domain_here>
IP4.SEARCHES[2]:                        <found_by_nm>
IP4.SEARCHES[3]:                        <found_by_nm>
```
Since it looks like network-manager found some other domains just from the inputted domain

**Comment by bbedward** [comment]
Here's a set of changes

https://github.com/AvengeMedia/danklinux/commit/3dc10ba23b6d5db70744adbee0ed5052e8cc3f56

https://github.com/AvengeMedia/DankMaterialShell/commit/0e215d69cb64c1f4f539c0af6909f8666eb02387

I'm pretty confident this is matching the good connection, at least for required fields.

```go
			settings["802-11-wireless-security"] = map[string]interface{}{
				"key-mgmt": "wpa-eap",
			}

			x := map[string]interface{}{
				"eap":             []string{"peap"},
				"phase2-auth":     "mschapv2",
				"identity":        req.Username,
				"password":        req.Password,
				"system-ca-certs": "no",
			}

			if req.AnonymousIdentity != "" {
				x["anonymous-identity"] = req.AnonymousIdentity
			}
			if req.DomainSuffixMatch != "" {
				x["domain-suffix-match"] = req.DomainSuffixMatch
			}

			settings["802-1x"] = x
```

**Comment by samminhch** [comment]
Hello, sorry for not getting back to you sooner, but I think there was a regression because it says "Connection Failed" as soon as I entered in my login details. The log is pasted below:

```
DankLinux Manager v0.1.15-8-g7e94124
...
2025/10/24 09:10:57 [ConnectWiFi] Starting connection to SSID: {SSID_HERE}, hasUsername: true, hasPassword: true
2025/10/24 09:10:57 [ConnectWiFi] Searching for existing connection for SSID: {SSID_HERE}
2025/10/24 09:10:58 [ConnectWiFi] No existing connection found (or error: connection not found), creating new connection
2025/10/24 09:10:58 [createAndConnectWiFi] Starting for SSID: {SSID_HERE}
2025/10/24 09:10:58 [createAndConnectWiFi] Ensuring WiFi device is available
2025/10/24 09:10:58 [createAndConnectWiFi] Getting access points
2025/10/24 09:10:58 [createAndConnectWiFi] Found 27 access points
2025/10/24 09:10:58 [createAndConnectWiFi] Found target access point for SSID: {SSID_HERE}
2025/10/24 09:10:58 [createAndConnectWiFi] AP Security flags - flags: 0x1, wpaFlags: 0x0, rsnFlags: 0x288
2025/10/24 09:10:58 [createAndConnectWiFi] Network analysis - secured: true, isEnterprise: true, isPsk: false, isSae: false
2025/10/24 09:10:58 [createAndConnectWiFi] WPA-EAP settings: eap=peap, phase2-auth=mschapv2, identity={USERNAME_HERE}, system-ca-certs=no, domain-suffix-match="{DOMAIN_HERE}"
2025/10/24 09:10:58 [createAndConnectWiFi] Calling AddAndActivateWirelessConnection with settings: map[802-11-wireless:map[mode:infrastructure security:802-11-wireless-security ssid:[67 111 109 101 116 78 101 116]] 802-11-wireless-security:map[key-mgmt:wpa-eap] 802-1x:map[domain-suffix-match:{DOMAIN_HERE} eap:[peap] identity:{USERNAME_HERE} password:{PASSWORD_HERE} phase2-auth:mschapv2 system-ca-certs:no] connection:map[id:{SSID_HERE} type:802-11-wireless] ipv4:map[method:auto] ipv6:map[method:auto]]
2025/10/24 09:10:58 [createAndConnectWiFi] Using access point: /org/freedesktop/NetworkManager/AccessPoint/2814
2025/10/24 09:10:58 [createAndConnectWiFi] ERROR: AddAndActivateWirelessConnection failed: Failed to determine AP security information
2025/10/24 09:10:58 [createAndConnectWiFi] ERROR: Connection settings that failed: map[802-11-wireless:map[mode:infrastructure security:802-11-wireless-security ssid:[67 111 109 101 116 78 101 116]] 802-11-wireless-security:map[key-mgmt:wpa-eap] 802-1x:map[domain-suffix-match:utdallas.edu eap:[peap] identity:{USERNAME_HERE} password:{PASSWORD_HERE} phase2-auth:mschapv2 system-ca-certs:no] connection:map[id:{SSID_HERE} type:802-11-wireless] ipv4:map[method:auto] ipv6:map[method:auto]]
2025/10/24 09:10:58 [ConnectWiFi] ERROR: Failed to create and connect: failed to connect: Failed to determine AP security information
 ERROR  go: DMS API Error: id=1761315058013 error=failed to connect: Failed to determine AP security information
 DEBUG qml: DMSService: Request socket << {"id":1761315058013,"error":"failed to connect: Failed to determine AP security information"}
 DEBUG qml: NetworkManagerService: Connection request failed: failed to connect: Failed to determine AP security information
```

**Comment by bbedward** [comment]
are you on the latest one? Just want to confirm since there was an addition of a secrets agent with networkmanager and stuff (which changes the flow a bit)

**Comment by samminhch** [comment]
Yes, I used `git pull` to get the latest version of `danklinux`, and I happened to get those errors when testing

**Comment by bbedward** [comment]
You also have the latest QML? The flow is a bit different but the logs I can't tell that it reflects it - it looks like the old, non-interactive no-agent mode.

On the latest everything it adds & activates the network, then gets a signal for the credentials (if needed) after. It looks like your logs aren't doing the interactive flow (since hasUsername hasPassword = true)
